In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


* Documentation for [pytorch](https://pytorch.org/).
* Pytorch [course](https://www.learnpytorch.io/).

## Basics

* [Tensor](https://pytorch.org/docs/stable/tensors.html) documentation.

### Uniform random values

* Random uniform values: [rand](https://pytorch.org/docs/stable/generated/torch.rand.html).

In [ ]:
# Random weights.
x = torch.rand(3, 3)
print(x)

tensor([[0.9738, 0.6288, 0.2334],
        [0.1176, 0.4930, 0.9220],
        [0.0585, 0.4581, 0.2332]])


In [ ]:
# Set seed.
torch.manual_seed(101)
x = torch.rand(3, 3)

torch.manual_seed(101)
y = torch.rand(3, 3)

assert torch.equal(x, y)

### Zeros and ones

In [ ]:
x = torch.zeros((4, 4))
x.fill_diagonal_(1)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [ ]:
y = torch.eye(4)
assert torch.equal(x, y)

### Sequences

* Range of values [arange](https://pytorch.org/docs/stable/generated/torch.arange.html).

In [ ]:
x = torch.arange(1, 4)
print(x)

tensor([1, 2, 3])


### Attributes

In [ ]:
# Data type.
x = torch.rand((2, 2))
x.dtype

torch.float32

In [ ]:
# Shape.
x.shape

torch.Size([2, 2])

In [ ]:
# Device.
x.device

device(type='cpu')

### Functions

* [Mathematical operations](https://pytorch.org/docs/stable/torch.html#math-operations).

In [ ]:
# Instantiate an empty tensor and fill with independent normal draws.
x = torch.empty((3, 3))
x.normal_()

tensor([[ 0.0957, -0.9350,  0.8415],
        [ 0.7698,  1.2430, -1.2957],
        [ 0.4824, -0.0120, -1.1334]])

In [ ]:
# Directly create a tensor with random normal draws.
x = torch.randn((3, 3))
print(x)

tensor([[ 0.6492,  1.5073,  0.4936],
        [ 0.7511, -1.0347, -1.9939],
        [-0.0589,  1.6477,  0.9796]])


In [ ]:
# Indicator matrix.
x.heaviside(torch.tensor(0.0))

tensor([[1., 1., 1.],
        [1., 0., 0.],
        [0., 1., 1.]])

In [ ]:
# Matrix multiplication.
xtx = x.t() @ x

In [ ]:
# SVD.
u, s, v = xtx.svd()
y = u @ torch.diag(s) @ v.t()
assert torch.allclose(xtx, y)

In [ ]:
# Minimum and maximum.
x = torch.randn((3, 3))
xmin = x.min()
xmax = x.max()

In [ ]:
# Sum and product.
xsum = x.sum()
xprd = x.prod()

In [ ]:
# Flatten.
x = torch.rand((3, 3, 3))
assert torch.equal(x.flatten(), x.view(-1))

In [ ]:
# Argmin and argmax.
imin = x.argmin()
assert x.view(-1)[imin] == x.min()

imax = x.argmax()
assert x.view(-1)[imax] == x.max()

### Combining tensors.

* [Concatenate](https://pytorch.org/docs/stable/generated/torch.cat.html).
* [Stack](https://pytorch.org/docs/stable/generated/torch.stack.html).

In [ ]:
x = torch.zeros((3, 2))
y = torch.ones((3, 2))

In [ ]:
# Concatenate horizontally.
z1 = torch.hstack((x, y))
print(z1)
z2 = torch.cat((x, y), dim=1)
assert torch.equal(z1, z2)

tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 1., 1.]])


In [ ]:
# Concatenate vertically.
z1 = torch.vstack((x, y))
print(z1)
z2 = torch.cat((x, y), dim=0)
assert torch.equal(z1, z2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
# Stack along the channel dimension.
# Cannot use concatenate here.
z = torch.stack((x, y), dim=2)
z.shape
assert torch.equal(
  torch.stack((x, y), dim=2),
  torch.stack((x, y), dim=-1)
)

### Reshaping
* [Reshaping](https://pytorch.org/docs/stable/generated/torch.reshape.html) will return a view if possible, and a copy if not.
* [Viewing](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) will raise an error if the new shape is not compatible with the original shape.

In [ ]:
x = torch.arange(1, 13)
x1 = x.reshape((12, 1))
x2 = x.reshape((6, 2))
x3 = x.reshape((4, 3))

In [ ]:
# Adding dimensions.
x = torch.arange(1, 4)
x = x.unsqueeze(dim=-1)
print(x.shape)

torch.Size([3, 1])


In [ ]:
# Permuting dimensions.
x = torch.zeros((4, 4, 3))
xt = x.permute((2, 0, 1))
print(xt.shape)

torch.Size([3, 4, 4])


In [ ]:
# Permutations are *views* of the original tensor.
x[0, 0, 0] = 1.0
print(xt[0, 0, 0])

tensor(1.)


### Slicing

In [ ]:
x = torch.arange(1, 10)
x = x.reshape(3, 3)
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
# First row.
x[0, :]

tensor([1, 2, 3])

In [ ]:
# First column.
x[:, 0]

tensor([1, 4, 7])

### NumPy conversion

In [ ]:
x = np.arange(1, 9)
y = torch.from_numpy(x)
z = torch.arange(1, 9)
torch.equal(y, z)

True

In [ ]:
np.array_equal(x, z.numpy())

True

### GPU
* Must connect to a GPU instance

In [ ]:
!nvidia-smi

Sat Jun 22 03:07:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
torch.cuda.device_count()

1

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [ ]:
x = torch.rand((3, 3))
print(x.device)

cpu


In [ ]:
x_gpu = x.to(device)
print(x_gpu.device)

cuda:0


In [ ]:
x_cpu = x_gpu.cpu()
print(x_cpu.device)

cpu
