In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


* Documentation for [pytorch](https://pytorch.org/).
* Pytorch [course](https://www.learnpytorch.io/).

## Basics

### Uniform random values

Random uniform values [`torch.rand`](https://pytorch.org/docs/stable/generated/torch.rand.html).

In [2]:
# Random weights.
x = torch.rand(3, 3)
print(x)

tensor([[0.9738, 0.6288, 0.2334],
        [0.1176, 0.4930, 0.9220],
        [0.0585, 0.4581, 0.2332]])


### Zeros and ones

In [3]:
x = torch.zeros((4, 4))
x.fill_diagonal_(1)
print(x)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [4]:
y = torch.eye(4)
assert torch.equal(x, y)

### Sequences

Range of values [`torch.arange`](https://pytorch.org/docs/stable/generated/torch.arange.html).

In [5]:
x = torch.arange(1, 4)
print(x)

tensor([1, 2, 3])


### Attributes

In [6]:
# Data type.
x = torch.rand((2, 2))
x.dtype

torch.float32

In [7]:
# Shape.
x.shape

torch.Size([2, 2])

In [8]:
# Device.
x.device

device(type='cpu')

### Functions

* [Mathematical operations](https://pytorch.org/docs/stable/torch.html#math-operations)

In [9]:
# Instantiate an empty tensor and fill with independent normal draws.
x = torch.empty((3, 3))
x.normal_()

tensor([[ 0.0957, -0.9350,  0.8415],
        [ 0.7698,  1.2430, -1.2957],
        [ 0.4824, -0.0120, -1.1334]])

In [10]:
# Directly create a tensor with random normal draws.
x = torch.randn((3, 3))
print(x)

tensor([[ 0.6492,  1.5073,  0.4936],
        [ 0.7511, -1.0347, -1.9939],
        [-0.0589,  1.6477,  0.9796]])


In [11]:
# Indicator matrix.
x.heaviside(torch.tensor(0.0))

tensor([[1., 1., 1.],
        [1., 0., 0.],
        [0., 1., 1.]])

In [12]:
# Matrix multiplication.
xtx = x.t() @ x

In [13]:
# SVD.
u, s, v = xtx.svd()
y = u @ torch.diag(s) @ v.t()
assert torch.allclose(xtx, y)

In [14]:
# Minimum and maximum.
x = torch.randn((3, 3))
xmin = x.min()
xmax = x.max()

In [15]:
# Sum and product.
xsum = x.sum()
xprd = x.prod()

In [16]:
# Flatten.
x = torch.rand((3, 3, 3))
assert torch.equal(x.flatten(), x.view(-1))

In [17]:
# Argmin and argmax.
imin = x.argmin()
assert x.view(-1)[imin] == x.min()

imax = x.argmax()
assert x.view(-1)[imax] == x.max()

### Combining tensors.

* [Concatenate](https://pytorch.org/docs/stable/generated/torch.cat.html).
* [Stack](https://pytorch.org/docs/stable/generated/torch.stack.html).

In [18]:
x = torch.zeros((3, 2))
y = torch.ones((3, 2))

In [19]:
# Concatenate horizontally.
z1 = torch.hstack((x, y))
print(z1)
z2 = torch.cat((x, y), dim=1)
assert torch.equal(z1, z2)

tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 1., 1.]])


In [20]:
# Concatenate vertically.
z1 = torch.vstack((x, y))
print(z1)
z2 = torch.cat((x, y), dim=0)
assert torch.equal(z1, z2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [21]:
# Stack along the channel dimension.
# Cannot use concatenate here.
z = torch.stack((x, y), dim=2)
z.shape
assert torch.equal(
  torch.stack((x, y), dim=2),
  torch.stack((x, y), dim=-1)
)

### Reshaping
* [Reshaping](https://pytorch.org/docs/stable/generated/torch.reshape.html) will return a view if possible, and a copy if not.
* [Viewing](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) will raise an error if the new shape is not compatible with the original shape.

In [22]:
x = torch.arange(1, 13)
x1 = x.reshape((12, 1))
x2 = x.reshape((6, 2))
x3 = x.reshape((4, 3))

In [23]:
# Adding dimensions.
x = torch.arange(1, 4)
x = x.unsqueeze(dim=-1)
print(x.shape)

torch.Size([3, 1])


In [24]:
x = x.squeeze()
x = x.unsqueeze(dim=0)
print(x.shape)

torch.Size([1, 3])
